### ISSUE TITLE
haikangcamera.cpp中的MV_FRAME_OUT未定义

### ISSUE THREAD

**Issue by Henry-APT** [wangyuou/QVision#2]
编译的过程中发现有一些头文件没有放在Repo里面，这些头文件从别处可以下载，没有大碍。有需要的我可以把这些头文件放进来。

但是编译过程中报错，提示MV_FRAME_OUT未定义，这个貌似旨在haikangcamera.cpp中出现，不知道具体是如何定义的。

**Comment by wangyuou** [comment]
需要下载海康威视的sdk导入下lib就好了。
